news = {
    "status":"ok",
    "feed":{
        "url":"https:\/\/apps.carleton.edu\/sustainability\/feeds\/blogs\/sustaining_carleton",
        "title":"News :: Carleton College",
        "link":"http:\/\/apps.carleton.edu\/sustainability\/news\/",
        "author":"",
        "description":"The latest posts from News",
        "image":""
    },
    "items":[
        {"title":"A Smart Investment",
        "pubDate":"2017-08-23 15:38:13",
        "link":"http:\/\/apps.carleton.edu\/sustainability\/news\/?story_id=1617282",
        "guid":"41e59a9a6600cab29be78da3747336b0",
        "author":"",
        "thumbnail":"",
        "description":"<p>You\u2019re likely to find backhoes and construction workers on the Carleton campus every summer. But this year we\u2019re particularly busy as we begin to implement the first phase of the Utilities Master Plan, approved by the trustees this past fall.<\/p>",
        "content":"<p>You\u2019re likely to find backhoes and construction workers on the Carleton campus every summer. But this year we\u2019re particularly busy as we begin to implement the first phase of the Utilities Master Plan, approved by the trustees this past fall.<\/p>",
        "enclosure":[],
        "categories":[]},

        {"title":"Reasons to Bike to Work",
        "pubDate":"2017-05-22 20:15:13",
        "link":"http:\/\/apps.carleton.edu\/sustainability\/news\/?story_id=1577774",
        "guid":"28d13dc84c263f78df13830b3f6e75ab",
        "author":"",
        "thumbnail":"",
        "description":"<p>The benefits of biking to work.<\/p>",
        "content":"<p>The benefits of biking to work.<\/p>",
        "enclosure":[],
        "categories":[]},

        {"title":"The Top Five Misplaced Waste Items at Carleton",
        "pubDate":"2017-05-18 18:17:00",
        "link":"http:\/\/apps.carleton.edu\/sustainability\/news\/?story_id=1576581",
        "guid":"d5be089bc887daf3128eb19fed4aa305",
        "author":"",
        "thumbnail":"",
        "description":"<p>The waste items that are misplaced the most at Carleton.<\/p>",
        "content":"<p>The waste items that are misplaced the most at Carleton.<\/p>",
        "enclosure":[],
        "categories":[]},

        {"title":"Interview with Ana Sontag about Waste Reduction at Spring Concert",
        "pubDate":"2017-05-17 21:11:12",
        "link":"http:\/\/apps.carleton.edu\/sustainability\/news\/?story_id=1576214",
        "guid":"2e26f893914a29286c9f3123220b193c",
        "author":"",
        "thumbnail":"",
        "description":"<p><strong>The efforts being taken to reduce waste at Spring Concert.<\/strong><\/p>",
        "content":"<p><strong>The efforts being taken to reduce waste at Spring Concert.<\/strong><\/p>",
        "enclosure":[],
        "categories":[]},

        {"title":"Top Five Real Foods to Eat Today",
        "pubDate":"2017-05-03 20:41:21",
        "link":"http:\/\/apps.carleton.edu\/sustainability\/news\/?story_id=1568591",
        "guid":"b8c8308169c2a796f9f2594b3685c6b9",
        "author":"",
        "thumbnail":"",
        "description":"<p>The top \"real foods' that are available on campus.<\/p>",
        "content":"<p>The top \"real foods' that are available on campus.<\/p>",
        "enclosure":[],
        "categories":[]},

        {"title":"Waste Audits",
        "pubDate":"2017-04-26 20:53:02",
        "link":"http:\/\/apps.carleton.edu\/sustainability\/news\/?story_id=1563951",
        "guid":"63b46cdbf7e23e85eae347d719286781",
        "author":"",
        "thumbnail":"",
        "description":"<p>Waste audit done on Facilities Deparment<\/p>",
        "content":"<p>Waste audit done on Facilities Deparment<\/p>",
        "enclosure":[],
        "categories":[]},

        {"title":"Climate Action Week 2017: Sustainability Solutions",
        "pubDate":"2017-02-09 14:55:42",
        "link":"http:\/\/apps.carleton.edu\/sustainability\/news\/?story_id=1525927",
        "guid":"4979c9a5a460ef68b25804d9508dbe0f",
        "author":"",
        "thumbnail":"",
        "description":"<p>Get ready for Climate Action Week 2017: Sustainability Solutions! Every winter, the Sustainability Office, in collaboration with student organizations and campus offices, hosts Climate Action Week, a series of events to educate and involve the community in sustainability efforts.<\/p>",
        "content":"<p>Get ready for Climate Action Week 2017: Sustainability Solutions! Every winter, the Sustainability Office, in collaboration with student organizations and campus offices, hosts Climate Action Week, a series of events to educate and involve the community in sustainability efforts.<\/p>",
        "enclosure":[],
        "categories":[]},

        {"title":"Bon App and Waste",
        "pubDate":"2016-10-27 16:32:19",
        "link":"http:\/\/apps.carleton.edu\/sustainability\/news\/?story_id=1487663",
        "guid":"00993b038034072adaeb7a7c6c7cf757",
        "author":"",
        "thumbnail":"",
        "description":"<p>Learn about Bon App's waste reduction efforts at Carleton!<\/p>",
        "content":"<p>Learn about Bon App's waste reduction efforts at Carleton!<\/p>",
        "enclosure":[],
        "categories":[]},

        {"title":"Harvesting at the Farm this Summer",
        "pubDate":"2016-09-29 15:37:03",
        "link":"http:\/\/apps.carleton.edu\/sustainability\/news\/?story_id=1474907",
        "guid":"1dbd5b43835ac11aa56a8de023c9b315",
        "author":"",
        "thumbnail":"",
        "description":"",
        "content":"",
        "enclosure":[],
        "categories":[]},

        {"title":"Welcome Back!",
        "pubDate":"2016-09-27 16:27:16",
        "link":"http:\/\/apps.carleton.edu\/sustainability\/news\/?story_id=1473812",
        "guid":"447eb923880ed4eaac45bad9a3e50222",
        "author":"",
        "thumbnail":"",
        "description":"<p>Get to know the Sustainability Office Staff for the 2016-2017 School Year!<\/p>",
        "content":"<p>Get to know the Sustainability Office Staff for the 2016-2017 School Year!<\/p>",
        "enclosure":[],
        "categories":[]},

        {"title":"History of Biking in Northfield",
        "pubDate":"2016-04-29 15:21:33",
        "link":"http:\/\/apps.carleton.edu\/sustainability\/news\/?story_id=1410329",
        "guid":"9ba1776508d15babe46afa4dab7f6594",
        "author":"",
        "thumbnail":"",
        "description":"<p>Article that details the history of biking in Northfield.\u00a0 Published in May 2014 by the Entertainment Guide and written by Susan Hvistendahl.<\/p>",
        "content":"<p>Article that details the history of biking in Northfield.\u00a0 Published in May 2014 by the Entertainment Guide and written by Susan Hvistendahl.<\/p>",
        "enclosure":[],
        "categories":[]}
    ]
}
export default { news }