events = {
    "status":"ok",
    "feed":{
        "url":"https:\/\/apps.carleton.edu\/sustainability\/feeds\/events",
        "title":"Carleton College Sustainability Events",
        "link":"http:\/\/apps.carleton.edu\/sustainability\/events\/",
        "author":"",
        "description":"Events from Sustainability",
        "image":""
    },
    "items":[
        {"title":"January 15 - International Film Forum: LAST CALL. THE LIMITS OF GROWTH",
        "pubDate":"",
        "link":"http:\/\/apps.carleton.edu\/sustainability\/events\/?event_id=1648121&amp;date=2018-01-15",
        "guid":"355d48fffcf1bde06dcfc380dce65c3a",
        "author":"",
        "thumbnail":"",
        "description":"Weitz Cinema, 7:00 pm",
        "content":"Weitz Cinema, 7:00 pm",
        "enclosure":[],
        "categories":[]},

        {"title":"January 17 - International Film Forum:  D. MEADOW'S: ENVISIONING A SUSTAINABLE WORLD",
        "pubDate":"",
        "link":"http:\/\/apps.carleton.edu\/sustainability\/events\/?event_id=1648128&amp;date=2018-01-17",
        "guid":"6b3b247375acb9b0ba53fcf6a5bbe4a6",
        "author":"",
        "thumbnail":"",
        "description":"Weitz Cinema, 7:00 pm",
        "content":"Weitz Cinema, 7:00 pm",
        "enclosure":[],
        "categories":[]},

        {"title":"January 22 - International Film Forum: DRYING FOR FREEDOM",
        "pubDate":"",
        "link":"http:\/\/apps.carleton.edu\/sustainability\/events\/?event_id=1648137&amp;date=2018-01-22",
        "guid":"2e6ad76080c1a681118fc49070c34bfa",
        "author":"",
        "thumbnail":"",
        "description":"Weitz Cinema, 7:00 pm",
        "content":"Weitz Cinema, 7:00 pm",
        "enclosure":[],
        "categories":[]},

        {"title":"January 23 - International Film Forum: KEEP ON ROLLING: THE DREAM OF THE AUTOMOBILE",
        "pubDate":"",
        "link":"http:\/\/apps.carleton.edu\/sustainability\/events\/?event_id=1648139&amp;date=2018-01-23",
        "guid":"4987d5ca5236a0cdb42e57d3150e3f31",
        "author":"",
        "thumbnail":"",
        "description":"Weitz Cinema, 7:00 pm",
        "content":"Weitz Cinema, 7:00 pm",
        "enclosure":[],
        "categories":[]},

        {"title":"January 24 - International Film Forum: DEEDEE HALLECK'S SELECTION OF WORKS",
        "pubDate":"",
        "link":"http:\/\/apps.carleton.edu\/sustainability\/events\/?event_id=1648142&amp;date=2018-01-24",
        "guid":"6b57db17c3b3b42f41474df35409aedb",
        "author":"",
        "thumbnail":"",
        "description":"Weitz Cinema, 7:00 pm",
        "content":"Weitz Cinema, 7:00 pm",
        "enclosure":[],
        "categories":[]},

        {"title":"January 29 - International Film Forum: TOMORROW",
        "pubDate":"",
        "link":"http:\/\/apps.carleton.edu\/sustainability\/events\/?event_id=1648145&amp;date=2018-01-29",
        "guid":"50f860f6082a589bdd6e41ed5190a7e1",
        "author":"",
        "thumbnail":"",
        "description":"Weitz Cinema, 7:00 pm",
        "content":"Weitz Cinema, 7:00 pm",
        "enclosure":[],
        "categories":[]},

        {"title":"February 12 - International Film Forum: SEED: THE UNTOLD STORY",
        "pubDate":"",
        "link":"http:\/\/apps.carleton.edu\/sustainability\/events\/?event_id=1648155&amp;date=2018-02-12",
        "guid":"ecf10be92742be93441754d5d37b87d9",
        "author":"",
        "thumbnail":"",
        "description":"Weitz Cinema, 7:00 pm",
        "content":"Weitz Cinema, 7:00 pm",
        "enclosure":[],
        "categories":[]},

        {"title":"February 17 - Climate Action Week 2018",
        "pubDate":"",
        "link":"http:\/\/apps.carleton.edu\/sustainability\/events\/?event_id=1659795&amp;date=2018-02-17",
        "guid":"7951e842a964d2ddf478404fd98f90fe",
        "author":"",
        "thumbnail":"",
        "description":"",
        "content":"",
        "enclosure":[],
        "categories":[]},

        {"title":"February 18 - Climate Action Week 2018",
        "pubDate":"",
        "link":"http:\/\/apps.carleton.edu\/sustainability\/events\/?event_id=1659795&amp;date=2018-02-18",
        "guid":"bb22185a84756730a4cc2f3cc2e7ee54",
        "author":"",
        "thumbnail":"",
        "description":"",
        "content":"",
        "enclosure":[],
        "categories":[]},

        {"title":"February 19 - Climate Action Week 2018",
        "pubDate":"",
        "link":"http:\/\/apps.carleton.edu\/sustainability\/events\/?event_id=1659795&amp;date=2018-02-19",
        "guid":"4b175e8dc61ea69df887660c3e8c12ca",
        "author":"",
        "thumbnail":"",
        "description":"",
        "content":"",
        "enclosure":[],
        "categories":[]},

        {"title":"February 19 - International Film Forum: THE RIVER",
        "pubDate":"",
        "link":"http:\/\/apps.carleton.edu\/sustainability\/events\/?event_id=1648157&amp;date=2018-02-19",
        "guid":"99898144da28065106f892119626f5d3",
        "author":"",
        "thumbnail":"",
        "description":"Weitz Cinema, 7:00 pm",
        "content":"Weitz Cinema, 7:00 pm",
        "enclosure":[],
        "categories":[]},

        {"title":"February 20 - Climate Action Week 2018",
        "pubDate":"",
        "link":"http:\/\/apps.carleton.edu\/sustainability\/events\/?event_id=1659795&amp;date=2018-02-20",
        "guid":"d1d49f522b08de504d21ee59a6542ab6",
        "author":"",
        "thumbnail":"",
        "description":"",
        "content":"",
        "enclosure":[],
        "categories":[]},

        {"title":"February 21 - Climate Action Week 2018",
        "pubDate":"",
        "link":"http:\/\/apps.carleton.edu\/sustainability\/events\/?event_id=1659795&amp;date=2018-02-21",
        "guid":"864b55290798c5b94caa3a575fa18c4b",
        "author":"",
        "thumbnail":"",
        "description":"",
        "content":"",
        "enclosure":[],
        "categories":[]},

        {"title":"February 22 - Climate Action Week 2018",
        "pubDate":"",
        "link":"http:\/\/apps.carleton.edu\/sustainability\/events\/?event_id=1659795&amp;date=2018-02-22",
        "guid":"04bee32b8505effc454c0d7963055cfc",
        "author":"",
        "thumbnail":"",
        "description":"",
        "content":"",
        "enclosure":[],
        "categories":[]},

        {"title":"February 23 - Climate Action Week 2018",
        "pubDate":"",
        "link":"http:\/\/apps.carleton.edu\/sustainability\/events\/?event_id=1659795&amp;date=2018-02-23",
        "guid":"add82b3e90678b463f4ed4c3c3112b11",
        "author":"",
        "thumbnail":"",
        "description":"",
        "content":"",
        "enclosure":[],
        "categories":[]},

        {"title":"February 24 - Climate Action Week 2018",
        "pubDate":"",
        "link":"http:\/\/apps.carleton.edu\/sustainability\/events\/?event_id=1659795&amp;date=2018-02-24",
        "guid":"16f981cf997661bb7367f674bd52c0e6",
        "author":"",
        "thumbnail":"",
        "description":"",
        "content":"",
        "enclosure":[],
        "categories":[]},

        {"title":"February 26 - International Film Forum: 500 YEARS",
        "pubDate":"",
        "link":"http:\/\/apps.carleton.edu\/sustainability\/events\/?event_id=1648162&amp;date=2018-02-26",
        "guid":"71ca0040b0a759bdcc0527932be66a24",
        "author":"",
        "thumbnail":"",
        "description":"Weitz Cinema, 7:00 pm",
        "content":"Weitz Cinema, 7:00 pm",
        "enclosure":[],
        "categories":[]}
    ]
}

export default { events }