const OverviewCards = [
    {
        title: 'Your Energy Use',
    },
    {
        title: 'Campus Energy Use',
    },
    {
        title: 'Energy Generated by Windmills',
    }
]

export default OverviewCards