const ExampleData = [
    {
        title: 'Your Energy Use',
        data: {day: [{y: 8, x: "Electricity"},
                     {y: 7, x: "Water"},
                     {y: 16, x: "Heat/AC"}],
               week: [{y: 16, x: "Electricity"},
                      {y: 16, x: "Water"},
                      {y: 16, x: "Heat/AC"}],
               month:[{y: 160, x: "Electricity"},
                      {y: 0, x: "Water"},
                      {y: 50, x: "Heat/AC"}],
               year: [{y: 32, x: "Electricity"},
                      {y: 40, x: "Water"},
                      {y: 90, x: "Heat/AC"}],
               },
        graphType: 'bar' ,
    },
    {
        title: 'Campus Energy Use',
        data: {day: [{y: 8, x: "Electricity"},
                     {y: 7, x: "Water"},
                     {y: 16, x: "Heat/AC"}],
               week: [{y: 16, x: "Electricity"},
                      {y: 16, x: "Water"},
                      {y: 16, x: "Heat/AC"}],
               month:[{y: 160, x: "Electricity"},
                      {y: 0, x: "Water"},
                      {y: 50, x: "Heat/AC"}],
               year: [{y: 32, x: "Electricity"},
                      {y: 40, x: "Water"},
                      {y: 90, x: "Heat/AC"}],
               },
        graphType: 'bar' ,
    },
    {
        title: 'Energy Generated on Campus',
        data: {day: [{y: 8, x: "Solar"},
                     {y: 7, x: "Wind"},
                     {y: 16, x: "Geothermal"}],
               week: [{y: 16, x: "Solar"},
                      {y: 16, x: "Wind"},
                      {y: 16, x: "Geothermal"}],
               month:[{y: 160, x: "Solar"},
                      {y: 0, x: "Wind"},
                      {y: 50, x: "Geothermal"}],
               year: [{y: 32, x: "Solar"},
                      {y: 40, x: "Wind"},
                      {y: 90, x: "Geothermal"}],
               },
        graphType: 'pie' ,
    }
]

export default ExampleData